### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by saraharmstrong314**
updated README documentation link with Sakshi's "what's next" part for AWS

### CODE REVIEW

**Comment by saraharmstrong314** [comment]
It's ok if you don't get this PR thru before the deadline; Mash has the updated documentation on his repo and website.

**Comment by sakshi360** [comment]
ok

**Comment by sakshi360** [comment]
no

**Comment by AdelRCh** [comment]
Done after the deadline (had to wait for the review period to be done)

**Pull request merged**
